### ISSUE TITLE
phantomjs is not installed on Heroku

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#600]
```
2018-08-01T11:53:45.120113+00:00 app[web.1]: https://osmand.net/help-online?id=privacy-policy:	Could not find an executable ["phantomjs"] on your path.

2018-08-01T11:53:45.122424+00:00 app[web.1]: I, [2018-08-01T11:53:45.122357 #4]  INFO -- : [d502fc58-8233-4784-b8f1-9bf72c3bf6a9] Completed 500 Internal Server Error in 8ms (ActiveRecord: 1.1ms)

2018-08-01T11:53:45.123590+00:00 app[web.1]: F, [2018-08-01T11:53:45.123237 #4] FATAL -- : [d502fc58-8233-4784-b8f1-9bf72c3bf6a9] Cliver::Dependency::NotFound (Could not find an executable ["phantomjs"] on your path.):

2018-08-01T11:53:45.123596+00:00 app[web.1]: [d502fc58-8233-4784-b8f1-9bf72c3bf6a9] lib/tosbackdoc.rb:25:in `scrape'

2018-08-01T11:53:45.123244+00:00 app[web.1]: F, [2018-08-01T11:53:45.123172 #4] FATAL -- : [d502fc58-8233-4784-b8f1-9bf72c3bf6a9]   

2018-08-01T11:53:45.123593+00:00 app[web.1]: F, [2018-08-01T11:53:45.123292 #4] FATAL -- : [d502fc58-8233-4784-b8f1-9bf72c3bf6a9]   

2018-08-01T11:53:45.123594+00:00 app[web.1]: F, [2018-08-01T11:53:45.123357 #4] FATAL -- : [d502fc58-8233-4784-b8f1-9bf72c3bf6a9] lib/tosbackdoc.rb:97:in `download_and_filter_with_xpath'

2018-08-01T11:53:45.123598+00:00 app[web.1]: [d502fc58-8233-4784-b8f1-9bf72c3bf6a9] app/controllers/documents_controller.rb:68:in `crawl'

2018-08-01T11:53:45.123600+00:00 app[web.1]: [d502fc58-8233-4784-b8f1-9bf72c3bf6a9] app/controllers/documents_controller.rb:27:in `create'
```

I also encountered this error (`Cliver::Dependency::NotFound (Could not find an executable ["phantomjs"] on your path.):`) locally, and resolved it by [installing phantomjs](https://github.com/tosdr/phoenix/commit/6bcdd63b955cf75e0c6e43ef1123b33593d7aaeb).

(Btw, it should also be noted that phantomjs [has been discontinued](https://github.com/ariya/phantomjs/issues/15344) now that both Firefox and Chrome have headless modes.)

**Comment by michielbdejong** [comment]
I added phantomjs as a buildpack in https://dashboard.heroku.com/apps/edit-tosdr-org/settings
