### ISSUE TITLE
500 error on https://edit.tosdr.org/services/194/annotate

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#663]

**Comment by michielbdejong** [comment]
```sh
ActionView::Template::Error (undefined method `+' for nil:NilClass):
    65:         </div>
    66:         <div class="panel-body documentContent" data-content="<%= doc.text %>"> 
    67:           <% offset = 0 %>
    68:           <% doc.snippets.each do |snippet| %>
    69:             <% if snippet[:pointId] %>
    70:               <p><%= link_to hide_tags(snippet[:text]), point_path(snippet[:pointId]), title: snippet[:title], :data => { :document_id => doc.id, :offset => offset }%></p>
    71:             <% else %>
app/models/document.rb:28:in `block in snippets'
app/models/document.rb:22:in `snippets'
app/views/services/annotate.html.erb:68:in `block in _app_views_services_annotate_html_erb__2845426619756279596_57162020'
app/views/services/annotate.html.erb:59:in `_app_views_services_annotate_html_erb__2845426619756279596_57162020'

**Comment by Vinnl** [comment]
Well, that explains why I couldn't reproduce it locally - I'd already fixed it with some unstaged changes when working on something unrelated :/
